@startuml
hide empty members

package ska_tmc_cdm.messages.mccscontroller {
	package allocate.py <<Rectangle>> {
		note as N1
			This module models the
			input for
			""MCCSController.Allocate()""
		end note
	}

	package releaseresources.py <<Rectangle>> {
		note as N2
			This module models the
			input for
			""MCCSController.ReleaseResources()""
		end note
	}
}

@enduml