@startuml
hide empty members
left to right direction

package ska_tmc_cdm.messages.mccscontroller {
	package releaseresources.py <<Rectangle>> {
		class ReleaseResourcesRequest {
			interface: str
			subarray_id : int
			release_all : bool
		}
	}
}

@enduml
