@startuml
hide empty members

package ska_tmc_cdm.messages.central_node {
    package assign_resources.py <<Rectangle>> {
        class DishAllocation {
            receptor_ids : List[str]
        }

        class MCCSAllocate {
            station_ids: List[List[int]],
            channel_blocks: List[int],
            subarray_beam_ids: List[int]
        }

        class Channel {
            count: int
            start: int
            stride: int
            freq_min : float
            freq_max : float
            link_map : List[List[int]]
        }

        class ScanType {
            st_id : str
            reference_frame : str
            ra : str
            dec : str
        }
        ScanType *-- "*" Channel

        class PbDependency {
            pb_id : str
            kind : List[str]
        }
         class ResourceConfiguration {
            csp_links: List, 
            receptors: List,
            receive_nodes: int
        }
        class PhaseDir {
            ra: List,
            dec: List, 
            reference_time: str, 
            reference_frame: str
        }
        class BeamConfiguration {
            beam_id: str,
            function: str,
            search_beam_id: int = None,
            timing_beam_id: int = None,
            vlbi_beam_id: int = None,
        }
        class ChannelConfiguration {
            channels_id: str, 
        }
        ChannelConfiguration  *-- "*" Channel
        class PolarisationConfiguration {
            polarisations_id: str,
            corr_type: List[str] = None  
        }

        class FieldConfiguration {
            field_id : str
            pointing_fqdn : List[str],
        }

        FieldConfiguration  *-- "*" PhaseDir

        class SDPWorkflow {
            name : str
            kind : str
            version : str
        }

        class ProcessingBlockConfiguration {
            pb_id : str
            parameters : Dict
        }
        ProcessingBlockConfiguration  *-- "1" SDPWorkflow
        ProcessingBlockConfiguration  *-- "*" PbDependency

        class ExecutionConfiguration {
            eb_id: str,
            max_length: int,
            context: Dict,
            fields: List[FieldConfiguration] = None,
        }
        ExecutionConfiguration  *-- "1" BeamConfiguration
        ExecutionConfiguration  *-- "*" ChannelConfiguration
        ExecutionConfiguration  *-- "1" PolarisationConfiguration
        ExecutionConfiguration  *-- "*" FieldConfiguration

        class SDPConfiguration {
            sdp_id : str
            max_length : float
            interface : str
        }
        SDPConfiguration *-- "*" ScanType
        SDPConfiguration *-- "*" ProcessingBlockConfiguration
        SDPConfiguration *-- "*" ExecutionConfiguration
        SDPConfiguration *-- "*" ResourceConfiguration

        class AssignResourcesRequest {
            interface : str
            transaction_id : str
            subarray_id : int
        }

        AssignResourcesRequest *-- "1" DishAllocation
        AssignResourcesRequest *-- "1" MCCSAllocate
        AssignResourcesRequest *-- "1" SDPConfiguration

        class AssignResourcesResponse
        AssignResourcesResponse *-- "1" DishAllocation
	}
}

@enduml
