@startuml
hide empty members

package ska_tmc_cdm.messages.central_node {
    package assign_resources.py <<Rectangle>> {
        class DishAllocation {
            receptor_ids : List[str]
        }

        class MCCSAllocate {
            station_ids: List[List[int]],
            channel_blocks: List[int],
            subarray_beam_ids: List[int]
        }

        class Channel {
            count: int
            start: int
            stride: int
            freq_min : float
            freq_max : float
            link_map : List[List[int]]
        }

        class ScanType {
            st_id : str
            reference_frame : str
            ra : str
            dec : str
        }
        ScanType *-- "*" Channel

        class PbDependency {
            pb_id : str
            pb_type : List[str]
        }

        class SDPWorkflow {
            name : str
            kind : str
            version : str
        }

        class ProcessingBlockConfiguration {
            pb_id : str
            parameters : Dict
        }
        ProcessingBlockConfiguration  *-- "1" SDPWorkflow
        ProcessingBlockConfiguration  *-- "*" PbDependency

        class SDPConfiguration {
            sdp_id : str
            max_length : float
            interface : str
        }
        SDPConfiguration *-- "*" ScanType
        SDPConfiguration *-- "*" ProcessingBlockConfiguration

        class AssignResourcesRequest {
            interface : str
            transaction_id : str
            subarray_id : int
        }

        AssignResourcesRequest *-- "1" DishAllocation
        AssignResourcesRequest *-- "1" MCCSAllocate
        AssignResourcesRequest *-- "1" SDPConfiguration

        class AssignResourcesResponse
        AssignResourcesResponse *-- "1" DishAllocation
	}
}

@enduml
