@startuml
scale 350 width
hide empty members
skinparam shadowing true
skinparam class {
BackgroundColor LightGoldenRodYellow
ArrowColor IndianRed
BorderColor IndianRed
BorderThickness 1.5
}
package ska_tmc_cdm.messages.central_node {
    package telescope_start.py <<Rectangle>> {
        class StartTelescopeRequest {
            subarray_id: Optional[int]
            interface: Optional[str]
            transaction_id: str
        }
}
@enduml