@startuml
scale 2000 width
!pragma useNewPackage
hide empty members

' Remove the following lines when VLBI, PSS and PST
' are added to CDM
remove VLBIConfiguration
remove PSTConfiguration
remove PSSConfiguration
remove VLBIConfigurationSchema
remove PSTConfigurationSchema
remove PSSConfigurationSchema

package ska.cdm.messages.subarray_node {
	package configure {
		package core.py <<Rectangle>> {
			class Target
			class PointingConfiguration
			class DishConfiguration
		}

		package csp.py <<Rectangle>> {
			class FSPConfiguration
			class CBFConfiguration
			class CommonConfiguration
			class SubarrayConfiguration
			class CSPConfiguration
			class PSSConfiguration
			class PSTConfiguration
			class VLBIConfiguration
		}

		package sdp.py <<Rectangle>> {
			class SDPConfiguration
		}

        package mccs.py <<Rectangle>> {
            class StnConfiguration
            class SubarrayBeamConfiguration
            class MCCSConfiguration
        }

		package tmc.py <<Rectangle>> {
			class TMCConfiguration
		}

		package ~__init__.py {
			class ConfigureRequest
		}
	}

    package scan.py <<Rectangle>> {
        class ScanRequest
    }
}

package ska.cdm.schemas.subarray_node {
	package configure as P2 {
		package core.py as P3 {
			class TargetSchema
			class PointingSchema
			class DishConfigurationSchema
			class ConfigureRequestSchema

			note top of TargetSchema
				This maps a ""Target""
				used in the context of
				a dish pointing
			end note

		}

		package csp.py as P4 {
			class FSPConfigurationSchema
			class CBFConfigurationSchema
			class CommonConfigurationSchema
			class SubarrayConfigurationSchema
			class CSPConfigurationSchema
			class PSSConfigurationSchema
			class PSTConfigurationSchema
			class VLBIConfigurationSchema
		}

		package sdp.py as P5 {
			class SDPConfigurationSchema
		}

		package tmc.py as P6 {
			class TMCConfigurationSchema
		}

        package mccs.py as P7 {
            class StnConfigurationSchema
            class SubarrayBeamConfigurationSchema
            class MCCSConfigurationSchema
        }
	}

	package scan.py as P1 {
		class ScanRequestSchema
	}
}

ScanRequestSchema --- ScanRequest

TargetSchema --- Target
PointingSchema --- PointingConfiguration
DishConfigurationSchema --- DishConfiguration
ConfigureRequestSchema --- ConfigureRequest

FSPConfigurationSchema --- FSPConfiguration
CBFConfigurationSchema --- CBFConfiguration
PSSConfigurationSchema --- PSSConfiguration
PSTConfigurationSchema --- PSTConfiguration
VLBIConfigurationSchema --- VLBIConfiguration
CommonConfigurationSchema --- CommonConfiguration
SubarrayConfigurationSchema --- SubarrayConfiguration
CSPConfigurationSchema --- CSPConfiguration

SDPConfigurationSchema --- SDPConfiguration

TMCConfigurationSchema --- TMCConfiguration

StnConfigurationSchema --- StnConfiguration
SubarrayBeamConfigurationSchema --- SubarrayBeamConfiguration
MCCSConfigurationSchema --- MCCSConfiguration

note as N1
	These classes map the same Python
	class to different JSON representations
	as required by the target systems
end note
N1 ------ TargetSchema
@enduml
