@startuml
hide empty members

package "ska_tmc_cdm.messages.subarray_node.configure" as base {

	package "receptorgroup.py" as _receptorgroup <<Rectangle>> {
        class ReceptorGroup {}
    }

	package "core.py" as _core <<Rectangle>> {

        enum LegacyTargetReferenceFrame {
            ICRS
            FK5
            SPECIAL"
        }

        class SpecialTarget {
            reference_frame = LegacyTargetReferenceFrame.SPECIAL
            target_name: str
        }

        class ICRSTarget {
            reference_frame = LegacyTargetReferenceFrame.ICRS
        }

        class FK5Target {
            reference_frame = LegacyTargetReferenceFrame.FK5
        }

		class _TargetBase {
			coord : astropy.SkyCoord
			target_name : str = ""
			ca_offset_arcsec: float = 0
			ie_offset_arcsec: float = 0
		}

        _TargetBase <|-up- FK5Target
        _TargetBase <|-up- ICRSTarget

        abstract class TargetUnion {}
        note left of TargetUnion
        <u>**DEPRECATED**</u>
        Superseded by
        ReceptorGroup
        end note

        TargetUnion <|--- ICRSTarget
        TargetUnion <|--- FK5Target
        TargetUnion <|--- SpecialTarget

        note top of ICRSTarget
        <u>**DEPRECATED**</u>
        Also importable as
        ""Target"" for backwards
        compatability.
        end note

		enum PointingCorrection {
			MAINTAIN
			UPDATE
			RESET
		}

		class PointingConfiguration {
			correction: Optional[PointingCorrection]
			wrap_sector: Optional[int]
		}
		PointingConfiguration *-- "0..1" TargetUnion
		PointingConfiguration *- "0..*" ReceptorGroup

		class DishConfiguration {
			receiver_band : ReceiverBand
		}

		enum ReceiverBand {
			BAND_1
			BAND_2
			BAND_5A
			BAND_5B
		}

	}

}

@enduml
