@startuml
hide empty members

package ska_tmc_cdm.messages.subarray_node.configure {

	package core.py <<Rectangle>> {

		class Target {
			coord : astropy.SkyCoord
			target_name : str = ""
			ca_offset_arcsec: float = 0
			ie_offset_arcsec: float = 0
		}

		enum PointingCorrection {
			MAINTAIN
			UPDATE
			RESET
		}

		class HolographyReceptorGroupConfig {
		    receptors: list
		    field: dict
		    projection: dict
		}

		enum HolographyPattern {
		    FIXED
		    MOSAIC
		    SPIRAL
		    RASTER
		    CONSTANT_VELOCITY
		    TABLE
		    HYPOTROCHOID
		}

		class TrajectoryConfig {
		    name: HolographyPattern
		    attrs: dict
		}

		class PointingConfiguration {
			correction: PointingCorrection
			groups: list[HolographyReceptorGroupConfig]
		}
		
		PointingConfiguration *-- "1" Target
		PointingConfiguration "1"-- "*" HolographyReceptorGroupConfig

		HolographyReceptorGroupConfig *-- "1" TrajectoryConfig

		class DishConfiguration {
			receiver_band : ReceiverBand
		}

		enum ReceiverBand {
			BAND_1
			BAND_2
			BAND_5A
			BAND_5B
		}

	}

}

@enduml
