@startuml
hide empty members

' Remove the following lines when VLBI, PSS and PST
' are added to CDM
remove VLBIConfiguration
remove PSTConfiguration
remove PSSConfiguration

set separator none 
package ska_tmc_cdm.messages.subarray_node.configure {
	package csp <<Rectangle>> {

	    class CommonConfiguration {
	        config_id: str
            frequency_band: core.ReceiverBand
            subarray_id: int
            band_5_tuning: List[float]
	    }

	    class CBFConfiguration {
            vlbi: dict
	    }

		enum FSPFunctionMode {
			CORR
			PSS-BF
			PST-BF
			VLBI
		}

		class FSPConfiguration {
			fsp_id : int
			function_mode : FSPFunctionMode
			integration_factor : int
			zoom_factor : int
			output_link_map : List[Tuple]
		}

		class CSPConfiguration {
	        interface: str
	        pss: dict
	        pst: dict

		}

		class LowCBFConfiguration {
			stations: StationConfiguration 
			vis: VisConfiguration
		}

		class StationConfiguration {
			stns: List[List[int]]
        	stn_beams: List[StnBeamConfiguration]
		}
		
		class StnBeamConfiguration {
			stn_beam_id: int
			freq_ids: List[int]
			host: [List[Tuple[int, str]]]
			port: [List[Tuple[int, int, int]]]
			mac: [List[Tuple[int, str]]]
			integration_ms: [int]
		}

		class VisConfiguration {
			fsp: VisFspConfiguration
			stn_beams: List[StnBeamConfiguration]
		}

		class VisFspConfiguration {
			function_mode: [str]
			fsp_ids: [List[int]]
		}

		CBFConfiguration *-- "*" FSPConfiguration
		CSPConfiguration *-- "1" CommonConfiguration
		CSPConfiguration *-- "1" SubarrayConfiguration
		CSPConfiguration *-- "0..1" CBFConfiguration
		CSPConfiguration *-- "1" LowCBFConfiguration
		LowCBFConfiguration *-- "1" StationConfiguration
		LowCBFConfiguration *-- "1" VisConfiguration
		VisConfiguration *-- "1" VisFspConfiguration
		VisConfiguration *-- "*" StnBeamConfiguration
		StationConfiguration *-- "*" StnBeamConfiguration
	}	
}
@enduml