@startuml
hide empty members

package ska_tmc_cdm.messages.subarray_node.configure {
    package mccs <<Rectangle>> {
        

        class SubarrayBeamAperatures {
            aperture_id: Optional[str]
            weighting_key_ref: Optional[str]
        }
        class SubarrayBeamLogicalBands {
            start_channel: Optional[int]
            number_of_channels: Optional[int]
        }

        class SubarrayBeamSkyCoordinates {
            reference_frame: Optional[str]
            c1: Optional[float]
            c2: Optional[float]
        }

        class SubarrayBeamConfiguration {
            update_rate: float
            logical_bands: List[SubarrayBeamLogicalBands]
            apertures: List[SubarrayBeamAperatures]
            sky_coordinates: SubarrayBeamSkyCoordinates
            subarray_beam_id: Optional[int]
        }

        class MCCSConfiguration {
            subarray_beam_configs: List[SubarrayBeamConfiguration],
        }
        MCCSConfiguration *-- "*" SubarrayBeamConfiguration
        SubarrayBeamConfiguration *-- "1" SubarrayBeamLogicalBands
        SubarrayBeamConfiguration *-- "1" SubarrayBeamAperatures
        SubarrayBeamConfiguration *-- "1" SubarrayBeamSkyCoordinates
    }
}

@enduml
