@startuml ska_tmc_cdm.messages.subarray_node.configure.pst
!pragma useIntermediatePackages false

class ska_tmc_cdm.messages.subarray_node.configure.pst.PSTBeamConfiguration {
  beam_id: int {static}
  scan: Optional[PSTScanConfiguration] {static}
}
class ska_tmc_cdm.messages.subarray_node.configure.pst.PSTChannelizationStageConfiguration {
  num_filter_taps: int {static}
  filter_coefficients: List[float] {static}
  num_frequency_channels: int {static}
  oversampling_ratio: List[int] {static}
}
class ska_tmc_cdm.messages.subarray_node.configure.pst.PSTConfiguration {
  beams: List[PSTBeamConfiguration] {static}
}
class ska_tmc_cdm.messages.subarray_node.configure.pst.PSTScanConfiguration {
  activation_time: str {static}
  bits_per_sample: int {static}
  num_of_polarizations: int {static}
  udp_nsamp: int {static}
  wt_nsamp: int {static}
  udp_nchan: int {static}
  num_frequency_channels: int {static}
  centre_frequency: float {static}
  total_bandwidth: float {static}
  observation_mode: str {static}
  observer_id: str {static}
  project_id: str {static}
  pointing_id: str {static}
  source: str {static}
  itrf: List[float] {static}
  receiver_id: str {static}
  feed_polarization: str {static}
  feed_handedness: int {static}
  feed_angle: float {static}
  feed_tracking_mode: str {static}
  feed_position_angle: float {static}
  oversampling_ratio: List[int] {static}
  coordinates: PSTScanCoordinates {static}
  max_scan_length: float {static}
  subint_duration: float {static}
  receptors: List[str] {static}
  receptor_weights: List[float] {static}
  num_channelization_stages: int {static}
  channelization_stages: List[PSTChannelizationStageConfiguration] {static}
}
class ska_tmc_cdm.messages.subarray_node.configure.pst.PSTScanCoordinates {
  equinox: float {static}
  ra: str {static}
  dec: str {static}
}
ska_tmc_cdm.messages.subarray_node.configure.pst.PSTBeamConfiguration *-- ska_tmc_cdm.messages.subarray_node.configure.pst.PSTScanConfiguration
ska_tmc_cdm.messages.subarray_node.configure.pst.PSTConfiguration *-- ska_tmc_cdm.messages.subarray_node.configure.pst.PSTBeamConfiguration
ska_tmc_cdm.messages.subarray_node.configure.pst.PSTScanConfiguration *-- ska_tmc_cdm.messages.subarray_node.configure.pst.PSTScanCoordinates
ska_tmc_cdm.messages.subarray_node.configure.pst.PSTScanConfiguration *-- ska_tmc_cdm.messages.subarray_node.configure.pst.PSTChannelizationStageConfiguration
footer Generated by //py2puml//
@enduml

